# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors cython pysam argparse ordereddict; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors cython pysam; fi"
  - python setup.py install
script: python setup.py test
